name: Test Makefile

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Pull images, pack benchmark, test-submission
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        proc: [ 'cpu' ]
    env:
      GITHUB_ACTIONS_NO_TTY: true

    steps:
      - uses: actions/checkout@v2

      - name: Create some fake data
        run: |
          pip install -U Pillow typer
          python runtime/scripts/generate_fake_inputs.py runtime/data/test_features

      - name: Test zipping benchmark
        run: |
          make pack-submission

      - name: Pull latest image and run submission in container
        run: |
          make pull
          make test-submission
